2024-01-05 23:07:18,169 INFO    MainThread:50718 [wandb_setup.py:_flush():68] Configure stats pid to 50718
2024-01-05 23:07:18,169 INFO    MainThread:50718 [wandb_setup.py:_flush():68] Loading settings from /home/paperspace/.config/wandb/settings
2024-01-05 23:07:18,169 INFO    MainThread:50718 [wandb_setup.py:_flush():68] Loading settings from /home/paperspace/Documents/plant_pathology/notebooks/wandb/settings
2024-01-05 23:07:18,169 INFO    MainThread:50718 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2024-01-05 23:07:18,169 INFO    MainThread:50718 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-05 23:07:18,169 INFO    MainThread:50718 [wandb_init.py:_log_setup():476] Logging user logs to /home/paperspace/Documents/plant_pathology/notebooks/wandb/run-20240105_230718-3b74y79t/logs/debug.log
2024-01-05 23:07:18,169 INFO    MainThread:50718 [wandb_init.py:_log_setup():477] Logging internal logs to /home/paperspace/Documents/plant_pathology/notebooks/wandb/run-20240105_230718-3b74y79t/logs/debug-internal.log
2024-01-05 23:07:18,170 INFO    MainThread:50718 [wandb_init.py:init():516] calling init triggers
2024-01-05 23:07:18,170 INFO    MainThread:50718 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'model_name': 'incep_v1', 'dataset_name': 'plant_pathology', 'epochs': 50, 'batch_size': 512, 'num_workers': 10, 'learning_rate': 0.001, 'optimizer': 'Adam', 'weights_path': '../../weights/incep_v1_hflip_rrotate_jitter_all_v3/', 'load_model': '../../weights/incep_v1_hflip_rrotate_jitter_all_v2/49.pth', 'normalize': True}
2024-01-05 23:07:18,170 INFO    MainThread:50718 [wandb_init.py:init():535] re-initializing run, found existing run on stack: 2azk0zvd
2024-01-05 23:07:18,171 INFO    MainThread:50718 [wandb_run.py:_finish():1746] finishing run yashchks87/plant_pathology/2azk0zvd
2024-01-05 23:07:18,171 INFO    MainThread:50718 [jupyter.py:save_history():448] not saving jupyter history
2024-01-05 23:07:18,171 INFO    MainThread:50718 [jupyter.py:save_ipynb():378] not saving jupyter notebook
2024-01-05 23:07:18,171 INFO    MainThread:50718 [wandb_init.py:_jupyter_teardown():408] cleaning up jupyter logic
2024-01-05 23:07:18,171 INFO    MainThread:50718 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2024-01-05 23:07:18,172 INFO    MainThread:50718 [wandb_run.py:_restore():1932] restore
2024-01-05 23:07:18,172 INFO    MainThread:50718 [wandb_run.py:_restore():1938] restore done
2024-01-05 23:07:25,383 INFO    MainThread:50718 [wandb_run.py:_footer_history_summary_info():3377] rendering history
2024-01-05 23:07:25,385 INFO    MainThread:50718 [wandb_run.py:_footer_history_summary_info():3409] rendering summary
2024-01-05 23:07:25,388 INFO    MainThread:50718 [wandb_run.py:_footer_sync_info():3333] logging synced files
2024-01-05 23:07:25,391 INFO    MainThread:50718 [wandb_init.py:init():569] starting backend
2024-01-05 23:07:25,391 INFO    MainThread:50718 [wandb_init.py:init():573] setting up manager
2024-01-05 23:07:25,393 INFO    MainThread:50718 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-01-05 23:07:25,393 INFO    MainThread:50718 [wandb_init.py:init():580] backend started and connected
2024-01-05 23:07:25,397 INFO    MainThread:50718 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2024-01-05 23:07:25,397 INFO    MainThread:50718 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-05 23:07:25,397 INFO    MainThread:50718 [wandb_init.py:init():658] updated telemetry
2024-01-05 23:07:25,463 INFO    MainThread:50718 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2024-01-05 23:07:26,592 INFO    MainThread:50718 [wandb_run.py:_on_init():2000] communicating current version
2024-01-05 23:07:26,636 INFO    MainThread:50718 [wandb_run.py:_on_init():2004] got version response upgrade_message: "wandb version 0.16.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-01-05 23:07:26,636 INFO    MainThread:50718 [wandb_init.py:init():728] starting run threads in backend
2024-01-05 23:07:26,667 INFO    MainThread:50718 [wandb_run.py:_console_start():1980] atexit reg
2024-01-05 23:07:26,667 INFO    MainThread:50718 [wandb_run.py:_redirect():1838] redirect: SettingsConsole.WRAP_RAW
2024-01-05 23:07:26,667 INFO    MainThread:50718 [wandb_run.py:_redirect():1903] Wrapping output streams.
2024-01-05 23:07:26,668 INFO    MainThread:50718 [wandb_run.py:_redirect():1925] Redirects installed.
2024-01-05 23:07:26,668 INFO    MainThread:50718 [wandb_init.py:init():765] run started, returning control to user process
2024-01-05 23:34:19,993 INFO    MainThread:50718 [wandb_setup.py:_flush():68] Configure stats pid to 50718
2024-01-05 23:34:19,993 INFO    MainThread:50718 [wandb_setup.py:_flush():68] Loading settings from /home/paperspace/.config/wandb/settings
2024-01-05 23:34:19,993 INFO    MainThread:50718 [wandb_setup.py:_flush():68] Loading settings from /home/paperspace/Documents/plant_pathology/notebooks/wandb/settings
2024-01-05 23:34:19,993 INFO    MainThread:50718 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2024-01-05 23:34:19,993 INFO    MainThread:50718 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-05 23:34:19,994 INFO    MainThread:50718 [wandb_init.py:_log_setup():476] Logging user logs to /home/paperspace/Documents/plant_pathology/notebooks/wandb/run-20240105_233419-1dtx4jkg/logs/debug.log
2024-01-05 23:34:19,994 INFO    MainThread:50718 [wandb_init.py:_log_setup():477] Logging internal logs to /home/paperspace/Documents/plant_pathology/notebooks/wandb/run-20240105_233419-1dtx4jkg/logs/debug-internal.log
2024-01-05 23:34:19,994 INFO    MainThread:50718 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f1666176190>
2024-01-05 23:34:19,994 INFO    MainThread:50718 [wandb_init.py:init():516] calling init triggers
2024-01-05 23:34:19,994 INFO    MainThread:50718 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'model_name': 'incep_v1', 'dataset_name': 'plant_pathology', 'epochs': 50, 'batch_size': 512, 'num_workers': 10, 'learning_rate': 0.001, 'optimizer': 'Adam', 'weights_path': '../../weights/incep_v1_hflip_rrotate_jitter_all_lr_change/', 'load_model': '../../weights/incep_v1_hflip_rrotate_jitter_all_v2/49.pth', 'normalize': True}
2024-01-05 23:34:19,994 INFO    MainThread:50718 [wandb_init.py:init():535] re-initializing run, found existing run on stack: 3b74y79t
2024-01-05 23:34:19,995 INFO    MainThread:50718 [wandb_run.py:_finish():1746] finishing run yashchks87/plant_pathology/3b74y79t
2024-01-05 23:34:19,996 INFO    MainThread:50718 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2024-01-05 23:34:19,996 INFO    MainThread:50718 [wandb_run.py:_restore():1932] restore
2024-01-05 23:34:19,996 INFO    MainThread:50718 [wandb_run.py:_restore():1938] restore done
2024-01-05 23:34:23,898 INFO    MainThread:50718 [wandb_run.py:_footer_history_summary_info():3377] rendering history
2024-01-05 23:34:23,900 INFO    MainThread:50718 [wandb_run.py:_footer_history_summary_info():3409] rendering summary
2024-01-05 23:34:23,904 INFO    MainThread:50718 [wandb_run.py:_footer_sync_info():3333] logging synced files
