2024-01-05 19:01:21,294 INFO    StreamThr :11310 [internal.py:wandb_internal():86] W&B internal server running at pid: 11310, started at: 2024-01-05 19:01:21.293143
2024-01-05 19:01:21,297 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: status
2024-01-05 19:01:21,302 INFO    WriterThread:11310 [datastore.py:open_for_write():85] open: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/run-qahs4m2a.wandb
2024-01-05 19:01:21,302 DEBUG   SenderThread:11310 [sender.py:send():382] send: header
2024-01-05 19:01:21,309 DEBUG   SenderThread:11310 [sender.py:send():382] send: run
2024-01-05 19:01:21,550 INFO    SenderThread:11310 [dir_watcher.py:__init__():211] watching files in: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files
2024-01-05 19:01:21,550 INFO    SenderThread:11310 [sender.py:_start_run_threads():1136] run started: qahs4m2a with start time 1704481281.292796
2024-01-05 19:01:21,561 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: check_version
2024-01-05 19:01:21,562 DEBUG   SenderThread:11310 [sender.py:send_request():409] send_request: check_version
2024-01-05 19:01:21,665 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: run_start
2024-01-05 19:01:21,675 DEBUG   HandlerThread:11310 [system_info.py:__init__():32] System info init
2024-01-05 19:01:21,676 DEBUG   HandlerThread:11310 [system_info.py:__init__():47] System info init done
2024-01-05 19:01:21,676 INFO    HandlerThread:11310 [system_monitor.py:start():194] Starting system monitor
2024-01-05 19:01:21,676 INFO    SystemMonitor:11310 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-01-05 19:01:21,677 INFO    HandlerThread:11310 [system_monitor.py:probe():214] Collecting system info
2024-01-05 19:01:21,677 INFO    SystemMonitor:11310 [interfaces.py:start():190] Started cpu monitoring
2024-01-05 19:01:21,679 INFO    SystemMonitor:11310 [interfaces.py:start():190] Started disk monitoring
2024-01-05 19:01:21,680 INFO    SystemMonitor:11310 [interfaces.py:start():190] Started gpu monitoring
2024-01-05 19:01:21,681 INFO    SystemMonitor:11310 [interfaces.py:start():190] Started memory monitoring
2024-01-05 19:01:21,682 INFO    SystemMonitor:11310 [interfaces.py:start():190] Started network monitoring
2024-01-05 19:01:21,697 DEBUG   HandlerThread:11310 [system_info.py:probe():196] Probing system
2024-01-05 19:01:21,700 DEBUG   HandlerThread:11310 [system_info.py:_probe_git():181] Probing git
2024-01-05 19:01:21,706 DEBUG   HandlerThread:11310 [system_info.py:_probe_git():189] Probing git done
2024-01-05 19:01:21,706 DEBUG   HandlerThread:11310 [system_info.py:probe():244] Probing system done
2024-01-05 19:01:21,707 DEBUG   HandlerThread:11310 [system_monitor.py:probe():223] {'os': 'Linux-6.2.0-37-generic-x86_64-with-glibc2.35', 'python': '3.10.12', 'heartbeatAt': '2024-01-05T19:01:21.698293', 'startedAt': '2024-01-05T19:01:21.285263', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'git': {'remote': 'https://github.com/yashchks87/plant_pathology.git', 'commit': 'e7ca672c0321a4e059c320454bd1c72cda725cf4'}, 'email': None, 'root': '/home/ubuntu/plant_pathology', 'host': '129-213-82-104', 'username': 'ubuntu', 'executable': '/usr/bin/python3', 'cpu_count': 30, 'cpu_count_logical': 30, 'cpu_freq': {'current': 2449.9980000000005, 'min': 0.0, 'max': 0.0}, 'cpu_freq_per_core': [{'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}, {'current': 2449.998, 'min': 0.0, 'max': 0.0}], 'disk': {'/': {'total': 496.0301856994629, 'used': 25.444828033447266}}, 'gpu': 'NVIDIA A100-SXM4-40GB', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA A100-SXM4-40GB', 'memory_total': 42949672960}], 'memory': {'total': 196.56491088867188}}
2024-01-05 19:01:21,707 INFO    HandlerThread:11310 [system_monitor.py:probe():224] Finished collecting system info
2024-01-05 19:01:21,707 INFO    HandlerThread:11310 [system_monitor.py:probe():227] Publishing system info
2024-01-05 19:01:21,707 DEBUG   HandlerThread:11310 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-01-05 19:01:21,708 DEBUG   HandlerThread:11310 [system_info.py:_save_pip():68] Saving pip packages done
2024-01-05 19:01:21,709 INFO    HandlerThread:11310 [system_monitor.py:probe():229] Finished publishing system info
2024-01-05 19:01:21,713 DEBUG   SenderThread:11310 [sender.py:send():382] send: files
2024-01-05 19:01:21,714 INFO    SenderThread:11310 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-01-05 19:01:21,724 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: stop_status
2024-01-05 19:01:21,724 DEBUG   SenderThread:11310 [sender.py:send_request():409] send_request: stop_status
2024-01-05 19:01:21,727 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 19:01:21,932 DEBUG   SenderThread:11310 [sender.py:send():382] send: telemetry
2024-01-05 19:01:22,035 INFO    wandb-upload_0:11310 [upload_job.py:push():131] Uploaded file /tmp/tmpeer63fykwandb/1sroc4td-wandb-metadata.json
2024-01-05 19:01:22,552 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:22,552 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/wandb-metadata.json
2024-01-05 19:01:22,553 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/requirements.txt
2024-01-05 19:01:24,551 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:26,500 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: status_report
2024-01-05 19:01:26,552 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:28,553 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:30,553 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:31,753 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: status_report
2024-01-05 19:01:32,554 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:33,994 ERROR   FileStreamThread:11310 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/yashchks87/plant_pathology/qahs4m2a/file_stream
NoneType: None
2024-01-05 19:01:34,554 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:35,998 ERROR   FileStreamThread:11310 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/yashchks87/plant_pathology/qahs4m2a/file_stream
NoneType: None
2024-01-05 19:01:36,555 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:36,725 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 19:01:36,725 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: stop_status
2024-01-05 19:01:36,726 DEBUG   SenderThread:11310 [sender.py:send_request():409] send_request: stop_status
2024-01-05 19:01:36,864 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: status_report
2024-01-05 19:01:38,003 ERROR   FileStreamThread:11310 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/yashchks87/plant_pathology/qahs4m2a/file_stream
NoneType: None
2024-01-05 19:01:38,556 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:40,006 ERROR   FileStreamThread:11310 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/yashchks87/plant_pathology/qahs4m2a/file_stream
NoneType: None
2024-01-05 19:01:40,557 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:41,138 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: partial_history
2024-01-05 19:01:41,143 DEBUG   SenderThread:11310 [sender.py:send():382] send: history
2024-01-05 19:01:41,143 DEBUG   SenderThread:11310 [sender.py:send_request():409] send_request: summary_record
2024-01-05 19:01:41,144 INFO    SenderThread:11310 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-01-05 19:01:41,557 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:41,557 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/wandb-summary.json
2024-01-05 19:01:42,007 ERROR   FileStreamThread:11310 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/yashchks87/plant_pathology/qahs4m2a/file_stream
NoneType: None
2024-01-05 19:01:42,028 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: status_report
2024-01-05 19:01:42,557 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:43,558 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:44,008 ERROR   FileStreamThread:11310 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/yashchks87/plant_pathology/qahs4m2a/file_stream
NoneType: None
2024-01-05 19:01:44,558 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:46,013 ERROR   FileStreamThread:11310 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/yashchks87/plant_pathology/qahs4m2a/file_stream
NoneType: None
2024-01-05 19:01:46,559 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:47,088 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: status_report
2024-01-05 19:01:48,019 ERROR   FileStreamThread:11310 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/yashchks87/plant_pathology/qahs4m2a/file_stream
NoneType: None
2024-01-05 19:01:48,058 ERROR   FileStreamThread:11310 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/yashchks87/plant_pathology/qahs4m2a/file_stream
NoneType: None
2024-01-05 19:01:48,560 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:50,023 ERROR   FileStreamThread:11310 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/yashchks87/plant_pathology/qahs4m2a/file_stream
NoneType: None
2024-01-05 19:01:50,560 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:51,726 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: stop_status
2024-01-05 19:01:51,726 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: internal_messages
2024-01-05 19:01:51,727 DEBUG   SenderThread:11310 [sender.py:send_request():409] send_request: stop_status
2024-01-05 19:01:52,026 ERROR   FileStreamThread:11310 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/yashchks87/plant_pathology/qahs4m2a/file_stream
NoneType: None
2024-01-05 19:01:52,352 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: status_report
2024-01-05 19:01:52,404 ERROR   SenderThread:11310 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-01-05 19:01:52,404 ERROR   SenderThread:11310 [internal_api.py:execute():374] {"errors":[{"message":"run yashchks87/plant_pathology/qahs4m2a was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-01-05 19:01:52,561 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:53,580 ERROR   SenderThread:11310 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-01-05 19:01:53,580 ERROR   SenderThread:11310 [internal_api.py:execute():374] {"errors":[{"message":"run yashchks87/plant_pathology/qahs4m2a was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-01-05 19:01:54,030 ERROR   FileStreamThread:11310 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/yashchks87/plant_pathology/qahs4m2a/file_stream
NoneType: None
2024-01-05 19:01:54,562 INFO    Thread-12 :11310 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ubuntu/plant_pathology/notebooks/wandb/run-20240105_190121-qahs4m2a/files/output.log
2024-01-05 19:01:56,096 ERROR   SenderThread:11310 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-01-05 19:01:56,096 ERROR   SenderThread:11310 [internal_api.py:execute():374] {"errors":[{"message":"run yashchks87/plant_pathology/qahs4m2a was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-01-05 19:01:56,096 INFO    SenderThread:11310 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-01-05 19:02:00,696 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: partial_history
2024-01-05 19:02:01,040 ERROR   SenderThread:11310 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-01-05 19:02:01,040 ERROR   SenderThread:11310 [internal_api.py:execute():374] {"errors":[{"message":"run yashchks87/plant_pathology/qahs4m2a was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-01-05 19:02:06,680 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: pause
2024-01-05 19:02:06,680 INFO    HandlerThread:11310 [handler.py:handle_request_pause():705] stopping system metrics thread
2024-01-05 19:02:06,680 INFO    HandlerThread:11310 [system_monitor.py:finish():203] Stopping system monitor
2024-01-05 19:02:06,681 DEBUG   SystemMonitor:11310 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-01-05 19:02:06,681 INFO    HandlerThread:11310 [interfaces.py:finish():202] Joined cpu monitor
2024-01-05 19:02:06,681 DEBUG   SystemMonitor:11310 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-01-05 19:02:06,682 DEBUG   SystemMonitor:11310 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-01-05 19:02:06,682 INFO    HandlerThread:11310 [interfaces.py:finish():202] Joined disk monitor
2024-01-05 19:02:06,745 INFO    HandlerThread:11310 [interfaces.py:finish():202] Joined gpu monitor
2024-01-05 19:02:06,746 INFO    HandlerThread:11310 [interfaces.py:finish():202] Joined memory monitor
2024-01-05 19:02:06,746 INFO    HandlerThread:11310 [interfaces.py:finish():202] Joined network monitor
2024-01-05 19:02:06,746 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: stop_status
2024-01-05 19:02:06,746 DEBUG   HandlerThread:11310 [handler.py:handle_request():146] handle_request: internal_messages
